[package]
name = "prestige"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
bootloader = "0.9.23"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
pc-keyboard = "0.6.1"
pic8259 = "0.10.2"
spin = "0.9.4"
uart_16550 = "0.2.18"
volatile = "0.4.5"
x86_64 = "0.14.10"
