[unstable] 
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = ".cargo/targets/x86_64-prestige.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"